name: CI Angular placeholder

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy to Vercel
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_9bmlnYQllkyUL6A9hCIzAMo88cIt/yzV0KNTKmX
